[env]
TERM = "xterm-256color"

[font]
size = 10

[font.normal]
family = "IosevkaTerm Nerd Font Mono"
style = "Regular"

[font.bold]
family = "IosevkaTerm Nerd Font Mono"
style = "Bold"

[font.italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Regular"

# [font.offset]
# y = 1

[shell]
program = "/bin/bash"

[window]
opacity = 0.9


[colors.bright]
black = "#747c84"
blue = "#ae95c7"
cyan = "#95aec7"
green = "#95c7ae"
magenta = "#c795ae"
red = "#c7ae95"
white = "#ffffff"
yellow = "#aec795"

[colors.normal]
black = "#1c2023"
blue = "#81a2be"
cyan = "#8abeb7"
green = "#8abeb7"
magenta = "#efaed4"
red = "#ff6b6b"
white = "#c7ccd1"
yellow = "#f0c674"

[colors.primary]
background = "#1c2023"
foreground = "#c7ccd1"
